name: tokenapp
description: A Flutter application to manage tokens.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  flutter_mobx: ^2.0.0
  mobx: ^2.0.0
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.0
  nb_utils: ^6.0.2
  lottie: ^2.7.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
   sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  flutter_lints: ^2.0.0 
flutter:
 uses-material-design: true  
 assets:
    - assets/icons/
    - assets/lottie/
    - assets/
    

 





